redis:
  url: 'redis://localhost:6379/1'
  semaphore:
    ns: 'bestelmaar_semaphore_test'
  sidekiq:
    ns: 'bestelmaar_sidekiq_test'
  session:
    ns: 'bestelmaar_session_test'

email:
  contact:
    to: 'bestelmaar@bureaupels.nl'
    from: 'no-reply@bureaupels.nl'
